name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update

      - name: Install xalan
        run: sudo apt-get install -y xalan

      - name: Install fop
        run: sudo apt-get install -y fop

      - name: build
        run: ant init

      - name: build
        run: ant build

      - name: copy
        run: ant copy-files

      - name: Archive results
        uses: actions/upload-artifact@v3.1.1
        with:
          name: FPV-OpenBook
          path: build
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    needs: build

    steps:
      
      - name: Get build results
        uses: actions/download-artifact@v3
        with:
          name: FPV-OpenBook

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload build GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
